### ISSUE TITLE
Error while encode

### ISSUE THREAD

**Issue by 3vangel1st** [evilsocket/ergo#6]
Getting the below error when I try to run the encode command to classify my malicious and clean files:

:~$ ergo encode malware/ data/ --output dataset.csv
[2019-05-29 03:41:35,405] (INFO) loading project /home/remnux/malware ...
[2019-05-29 03:41:35,410] (INFO) building model for training ...
[2019-05-29 03:41:35,449] (WARNING) From /usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
[2019-05-29 03:41:35,465] (WARNING) From /usr/local/lib/python3.4/dist-packages/keras/backend/tensorflow_backend.py:3445: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
[2019-05-29 03:41:35,509] (INFO) using auto labeling
[2019-05-29 03:41:35,510] (INFO) enumerating data/clean ...
[2019-05-29 03:41:35,510] (INFO) enumerating data/malicious ...
[2019-05-29 03:41:35,510] (INFO) labeling 0 files ...
[2019-05-29 03:41:35,510] (INFO) starting 8 workers for encoding
[2019-05-29 03:41:35,522] (INFO) encoding 0 inputs to dataset.csv ...

Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.4/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/usr/lib/python3.4/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.4/dist-packages/ergo/actions/encode.py", line 86, in appender
    on_progress(done, total)
  File "/usr/local/lib/python3.4/dist-packages/ergo/actions/encode.py", line 70, in on_progress
    perc  = done / total
ZeroDivisionError: division by zero

**Comment by evilsocket** [comment]
`[2019-05-29 03:41:35,522] (INFO) encoding 0 inputs to dataset.csv ...`

you are using it wrong

**Comment by evilsocket** [comment]
the syntax is:

    ergo encode MODEL_PATH DATA_PATH --output dataset.csv --filter "*.exe"

Where:

- MODEL_PATH is the folder of your ergo project
- DATA_PATH is a folder, containing one subfolder per class, each subfolder containing the samples of that class (for instance, DATA_PATH/malware and DATA_PATH/clean)
- `--filter` will determine which files will be encoded.

**Comment by 3vangel1st** [comment]
Many thanks for your feedback - will try it again

**Comment by 3vangel1st** [comment]
executed the syntax and getting the following part:

[2019-05-30 03:17:39,230] (INFO) loading project /home/remnux/malware ...
[2019-05-30 03:17:39,231] (INFO) building model for training ...
[2019-05-30 03:17:39,269] (WARNING) From /home/remnux/ergoproject/lib/python3.4/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
[2019-05-30 03:17:39,283] (WARNING) From /home/remnux/ergoproject/lib/python3.4/site-packages/keras/backend/tensorflow_backend.py:3445: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
[2019-05-30 03:17:39,328] (INFO) using auto labeling
[2019-05-30 03:17:39,328] (INFO) enumerating data/clean ...
[2019-05-30 03:17:39,331] (INFO) enumerating data/malicious ...
[2019-05-30 03:17:39,334] (INFO) labeling 0 files ...
[2019-05-30 03:17:39,334] (INFO) starting 8 workers for encoding
[2019-05-30 03:17:39,343] (INFO) encoding 0 inputs to dataset.csv ...

Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.4/multiprocessing/process.py", line 254, in _bootstrap
    self.run()
  File "/usr/lib/python3.4/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/remnux/ergoproject/lib/python3.4/site-packages/ergo/actions/encode.py", line 86, in appender
    on_progress(done, total)
  File "/home/remnux/ergoproject/lib/python3.4/site-packages/ergo/actions/encode.py", line 70, in on_progress
    perc  = done / total
ZeroDivisionError: division by zero
