### ISSUE TITLE
Error while train the model

### ISSUE THREAD

**Issue by 3vangel1st** [evilsocket/ergo#8]
Apologies to bother again. Using the provided dataset from your blog, but getting the below error-stack. What am I doing wrong?

(ergoproject) remnux@remnux:~$ ergo train malware --dataset dataset.csv 
[2019-05-30 09:48:29,475] (INFO) loading project /home/remnux/malware ...
[2019-05-30 09:48:29,476] (INFO) building model for training ...
[2019-05-30 09:48:29,496] (WARNING) From /home/remnux/ergoproject/lib/python3.4/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
[2019-05-30 09:48:29,507] (WARNING) From /home/remnux/ergoproject/lib/python3.4/site-packages/keras/backend/tensorflow_backend.py:3445: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
[2019-05-30 09:48:29,550] (INFO) preparing data from dataset.csv ...
[2019-05-30 09:48:45,318] (INFO) data shape: (199970, 487)
[2019-05-30 09:48:45,985] (CRITICAL) 'str' object has no attribute 'shape'
[2019-05-30 09:48:45,985] (ERROR) 

Traceback (most recent call last):
  File "/home/remnux/ergoproject/bin/ergo", line 81, in main
    ACTIONS[action].cb(argc - 2, sys.argv[2:])
  File "/home/remnux/ergoproject/lib/python3.4/site-packages/ergo/actions/train.py", line 62, in action_train
    prj.prepare(args.dataset, args.test, args.validation, not args.no_shuffle)
  File "/home/remnux/ergoproject/lib/python3.4/site-packages/ergo/project.py", line 143, in prepare
    return self.dataset.source(data, p_test, p_val, shuffle)
  File "/home/remnux/ergoproject/lib/python3.4/site-packages/ergo/dataset.py", line 113, in source
    log.info("detected non scalar input: %s", x.shape)
AttributeError: 'str' object has no attribute 'shape'

**Comment by evilsocket** [comment]
may i have a `head dataset.csv` ?

**Comment by 3vangel1st** [comment]
pe-malicious,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0627450980392,0.247058823529,0.611764705882,0.0196078431373,0.894117647059,0.752941176471,0.811764705882,0.458823529412,0.513725490196,0.639215686275,0.619607843137,0.509803921569,0.18431372549,0.705882352941,0.21568627451,0.725490196078,0.83137254902,0.776470588235,0.874509803922,0.427450980392,0.525490196078,0.0941176470588,0.360784313725,0.745098039216,0.180392156863,0.705882352941,0.294117647059,0.996078431373,0.078431372549,0.262745098039,0.223529411765,0.443137254902,0.650980392157,0.752941176471,0.690196078431,0.949019607843,0.356862745098,0.0313725490196,0.721568627451,0.509803921569,0.517647058824,0.76862745098,0.737254901961,0.964705882353,0.670588235294,0.262745098039,0.223529411765,0.443137254902,0.650980392157,0.752941176471,0.501960784314,0.949019607843,0.223529411765,0.160784313725,0.294117647059,0.509803921569,0.18431372549,0.478431372549,0.454901960784,0.588235294118,0.63137254902,0.117647058824,0.223529411765,0.0862745098039,0.0587804860067,0.00308915037306,0.00244035506798,0.00643081482792,0.00188556135539,0.00112248960453,0.00542260166917,0.00162014509422,0.00393147836857,0.00923427408653,0.00509636084815,0.00581888289245,0.00312970007962,0.00514981273408,0.0109392049308,0.0032918989059,0.00262282874753,0.00112433277301,0.00159802707246,0.00217493880681,0.0117151788611,0.00207540770887,0.00293985372615,0.00321079949276,0.00186344333363,0.00207356454039,0.00183210946946,0.00329005573741,0.00253804299743,0.00188556135539,0.00216387979592,0.0018192072901,0.00319605414492,0.0026633784541,0.00152982983869,0.00325319236781,0.00564378188681,0.00157959538766,0.0110995605886,0.00258412220944 and more ;)

**Comment by 3vangel1st** [comment]
you can close the issue - managed to install the dev version of Lief for Python3.7 - that fixed the issue.
